name: Deployment
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4 # the runner ubuntu-latest comes with nodejs by default
        with:
          node-version: 22
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
      - name: Install Packages
        run: pnpm install --frozen-lockfile
        # run: npm ci # This is better for production. If want to install dependencies requires to run prod. --only=production
      - name: Run test
        run: pnpm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4 # the runner ubuntu-latest comes with nodejs by default
        with:
          node-version: 22
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
      - name: Install Packages
        run: pnpm install --frozen-lockfile --prod # don't need --prod if NODE_ENV is set to production
        # run: npm ci --only# This is better for production. If want to install dependencies requires to run prod. --only=production
      - name: Deploy
        run: echo "Deploying"
